route:
  receiver: 'all'
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1m

receivers:
  - name: 'all'
    webhook_configs:
      - url: 'http://springboot:8080/alerts'
        send_resolved: true