version: '3.9'

networks:
  ai-network:
    driver: bridge

services:
  postgres:
    image: postgres:15
    container_name: ai-postgres
    environment:
      POSTGRES_DB: ai_assistant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - ai-network

  ollama:
    image: ollama/ollama
    container_name: ai-ollama
    ports:
      - "11434:11434"
    volumes:
      - /Users/ashishyadav/.ollama/models:/root/.ollama/models
    networks:
      - ai-network

  alertmanager:
    image: prom/alertmanager
    container_name: ai-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - ai-network
    depends_on:
      - springboot

  prometheus:
    image: prom/prometheus
    container_name: ai-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert-rules.yml:/etc/prometheus/alert-rules.yml
    depends_on:
      - springboot
    networks:
      - ai-network

  grafana:
    image: grafana/grafana
    container_name: ai-grafana
    ports:
      - "3000:3000"
    networks:
      - ai-network

  springboot:
    build: .
    container_name: ai-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - ollama
    networks:
      - ai-network

volumes:
  ollama-data: