spring.application.name=ai-assistant

spring.datasource.url=jdbc:postgresql://postgres:5432/ai_assistant
#spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.h2.console.enabled=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true